name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build for Linux
        env:
          GOOS: linux
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -v -o cosmos-exporter-linux-${{ matrix.arch }} ./cmd/main.go
          tar -czvf cosmos-exporter-linux-${{ matrix.arch }}.tar.gz cosmos-exporter-linux-${{ matrix.arch }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cosmos-exporter-linux-${{ matrix.arch }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
